Update status-check-functions.yml

diff --git a/.github/workflows/status-check-functions.yml b/.github/workflows/status-check-functions.yml
--- a/.github/workflows/status-check-functions.yml
+++ b/.github/workflows/status-check-functions.yml
@@ -2,7 +2,7 @@ name: Status Check Functions
 
 on:
   push:
-  workflow_dispatch: 
+  workflow_dispatch:
 
 jobs:
   eco-status-check-functions:
@@ -19,32 +19,30 @@ jobs:
           echo "Setting up the environment"
         
       - name: Task-1
+        id: task-1
         run: |
           echo "Working on the task-1"
           echo "Task-1: Success"
-          
+        
       - name: Task-2
+        id: task-2
         run: |
           echo "Working on the task-2"
-          exit 1 
+          exit 1  # This will cause Task-2 to fail
         
       - name: Check if Task-1 was successful
+        if: ${{ steps.task-1.outcome == 'success' }}
         run: |
-          if ${{ success() }}; then
-            echo "Task-1 was successful."
-          else
-            echo "Task-1 failed."
+          echo "Task-1 was successful."
         
       - name: Check if Task-2 was successful
+        if: ${{ steps.task-2.outcome == 'failure' }}
         run: |
-          if ${{ failure() }}; then
-            echo "Task-2 failed as expected."
-          else
-            echo "Task-2 succeeded unexpectedly."
+          echo "Task-2 failed as expected."
         
       - name: Always run this step
         run: |
-          echo "This step always runs incase of success or failure."
+          echo "This step always runs in case of success or failure."
         
       - name: Check workflow canceled
         run: |
@@ -56,5 +54,4 @@ jobs:
       - name: Final Status
         run: |
           echo "Final status: ${{ env.projectStatus }}"
-          echo " output is: ${{ fromjson(env.userJSON).name }} - Role: ${{ fromjson(env.userJSON).role }}"
-
+          echo "output is: ${{ fromjson(env.userJSON).name }} - Role: ${{ fromjson(env.userJSON).role }}"
